version: "3.8"

services:
  backend:
    restart: "unless-stopped"
    container_name: crypto-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    command: >
      sh -c "python wsgi.py"
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge
